# Generated by Django 6.0 on 2025-12-25 18:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifactuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable Verifactu compliance', verbose_name='Enabled')),
                ('mode', models.CharField(choices=[('verifactu', 'VERI*FACTU (Real-time transmission)'), ('no_verifactu', 'NO VERI*FACTU (Local storage)')], default='verifactu', help_text='VERIFACTU mode transmits in real-time to AEAT', max_length=20, verbose_name='Mode')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('testing', 'Testing (Staging)')], default='testing', help_text='Use Testing for development, Production for live data', max_length=20, verbose_name='Environment')),
                ('software_name', models.CharField(default='ERPlora Hub', help_text='Name of the invoicing software', max_length=100, verbose_name='Software Name')),
                ('software_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Software Version')),
                ('software_id', models.CharField(default='ERPLORA-001', help_text='Unique identifier for the software', max_length=50, verbose_name='Software ID')),
                ('software_nif', models.CharField(blank=True, help_text='NIF of the software provider company', max_length=15, verbose_name='Software Provider NIF')),
                ('certificate_path', models.CharField(blank=True, help_text='Path to PKCS#12 certificate file (.p12/.pfx)', max_length=500, verbose_name='Certificate Path')),
                ('certificate_password', models.CharField(blank=True, help_text='Encrypted password for certificate', max_length=200, verbose_name='Certificate Password')),
                ('certificate_expiry', models.DateField(blank=True, help_text='Expiration date of the certificate', null=True, verbose_name='Certificate Expiry')),
                ('auto_transmit', models.BooleanField(default=True, help_text='Automatically transmit records to AEAT', verbose_name='Auto Transmit')),
                ('retry_interval_minutes', models.PositiveIntegerField(default=5, help_text='Minutes between retry attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Retry Interval (minutes)')),
                ('max_retries', models.PositiveIntegerField(default=10, help_text='Maximum number of retry attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Max Retries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verifactu Configuration',
                'verbose_name_plural': 'Verifactu Configuration',
            },
        ),
        migrations.CreateModel(
            name='VerifactuRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('alta', 'Registration (Alta)'), ('anulacion', 'Cancellation (Anulación)')], default='alta', max_length=20, verbose_name='Record Type')),
                ('sequence_number', models.PositiveIntegerField(help_text='Sequential number for hash chain ordering', verbose_name='Sequence Number')),
                ('issuer_nif', models.CharField(max_length=15, verbose_name='Issuer NIF')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Issuer Name')),
                ('invoice_number', models.CharField(max_length=60, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('invoice_type', models.CharField(choices=[('F1', 'F1 - Standard Invoice'), ('F2', 'F2 - Simplified Invoice'), ('F3', 'F3 - Invoice substituting simplified'), ('R1', 'R1 - Rectifying (Art. 80.1-2)'), ('R2', 'R2 - Rectifying (Art. 80.3)'), ('R3', 'R3 - Rectifying (Art. 80.4)'), ('R4', 'R4 - Rectifying (other)'), ('R5', 'R5 - Rectifying simplified')], default='F1', max_length=5, verbose_name='Invoice Type')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Base Amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Amount')),
                ('previous_hash', models.CharField(blank=True, help_text='SHA-256 hash of previous record (empty for first record)', max_length=64, verbose_name='Previous Hash')),
                ('record_hash', models.CharField(help_text='SHA-256 hash of this record', max_length=64, verbose_name='Record Hash')),
                ('is_first_record', models.BooleanField(default=False, help_text='True if this is the first record in the chain', verbose_name='Is First Record')),
                ('generation_timestamp', models.DateTimeField(help_text='Exact moment of record generation (with timezone)', verbose_name='Generation Timestamp')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transmitted', 'Transmitted'), ('accepted', 'Accepted by AEAT'), ('rejected', 'Rejected by AEAT'), ('error', 'Transmission Error'), ('retry', 'Pending Retry')], default='pending', max_length=20, verbose_name='Status')),
                ('transmission_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Transmission Timestamp')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Retry At')),
                ('aeat_response_code', models.CharField(blank=True, max_length=20, verbose_name='AEAT Response Code')),
                ('aeat_response_message', models.TextField(blank=True, verbose_name='AEAT Response Message')),
                ('aeat_csv', models.CharField(blank=True, help_text='Secure Verification Code from AEAT', max_length=100, verbose_name='AEAT CSV')),
                ('qr_url', models.URLField(blank=True, verbose_name='QR Verification URL')),
                ('qr_generated', models.BooleanField(default=False, verbose_name='QR Generated')),
                ('xml_content', models.TextField(blank=True, help_text='Generated XML for this record', verbose_name='XML Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifactu_records', to='invoicing.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Verifactu Record',
                'verbose_name_plural': 'Verifactu Records',
                'ordering': ['-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='VerifactuEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('record_created', 'Record Created'), ('transmission_attempt', 'Transmission Attempt'), ('transmission_success', 'Transmission Success'), ('transmission_failure', 'Transmission Failure'), ('retry_scheduled', 'Retry Scheduled'), ('connection_error', 'Connection Error'), ('aeat_error', 'AEAT Error'), ('chain_validation', 'Chain Validation'), ('chain_error', 'Chain Error'), ('certificate_warning', 'Certificate Warning'), ('config_changed', 'Configuration Changed'), ('contingency_start', 'Contingency Mode Started'), ('contingency_end', 'Contingency Mode Ended')], max_length=30, verbose_name='Event Type')),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10, verbose_name='Severity')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details in JSON format', verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='verifactu.verifacturecord', verbose_name='Related Record')),
            ],
            options={
                'verbose_name': 'Verifactu Event',
                'verbose_name_plural': 'Verifactu Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContingencyQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2, verbose_name='Priority')),
                ('queued_at', models.DateTimeField(auto_now_add=True, verbose_name='Queued At')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Attempt At')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Attempt At')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contingency_entry', to='verifactu.verifacturecord', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'Contingency Queue Entry',
                'verbose_name_plural': 'Contingency Queue',
                'ordering': ['priority', 'queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verifacturecord',
            index=models.Index(fields=['status'], name='verifactu_v_status_63f08f_idx'),
        ),
        migrations.AddIndex(
            model_name='verifacturecord',
            index=models.Index(fields=['issuer_nif', 'invoice_number'], name='verifactu_v_issuer__eb5710_idx'),
        ),
        migrations.AddIndex(
            model_name='verifacturecord',
            index=models.Index(fields=['generation_timestamp'], name='verifactu_v_generat_6e1096_idx'),
        ),
        migrations.AddIndex(
            model_name='verifacturecord',
            index=models.Index(fields=['sequence_number'], name='verifactu_v_sequenc_3dd44b_idx'),
        ),
        migrations.AddConstraint(
            model_name='verifacturecord',
            constraint=models.UniqueConstraint(fields=('issuer_nif', 'invoice_number', 'invoice_date', 'record_type'), name='unique_verifactu_record'),
        ),
        migrations.AddIndex(
            model_name='verifactuevent',
            index=models.Index(fields=['event_type'], name='verifactu_v_event_t_59b288_idx'),
        ),
        migrations.AddIndex(
            model_name='verifactuevent',
            index=models.Index(fields=['severity'], name='verifactu_v_severit_7ad575_idx'),
        ),
        migrations.AddIndex(
            model_name='verifactuevent',
            index=models.Index(fields=['timestamp'], name='verifactu_v_timesta_f74097_idx'),
        ),
    ]
