# Generated by Django 6.0 on 2025-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingencyqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
