# Generated by Django 6.0 on 2025-12-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifactuconfig',
            name='first_record_date',
            field=models.DateField(blank=True, help_text='Date of first Verifactu record - audit trail', null=True, verbose_name='First Record Date'),
        ),
        migrations.AddField(
            model_name='verifactuconfig',
            name='fiscal_year_locked',
            field=models.PositiveIntegerField(blank=True, help_text='Fiscal year when mode was locked', null=True, verbose_name='Fiscal Year Locked'),
        ),
        migrations.AddField(
            model_name='verifactuconfig',
            name='mode_locked',
            field=models.BooleanField(default=False, help_text='True when mode cannot be changed (first invoice created)', verbose_name='Mode Locked'),
        ),
        migrations.AddField(
            model_name='verifactuconfig',
            name='mode_locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when mode was locked', null=True, verbose_name='Mode Locked At'),
        ),
        migrations.AddField(
            model_name='verifactuconfig',
            name='mode_locked_by',
            field=models.UUIDField(blank=True, help_text='UUID of user who created the first invoice', null=True, verbose_name='Mode Locked By'),
        ),
        migrations.AddField(
            model_name='verifactuconfig',
            name='module_activated',
            field=models.BooleanField(default=False, help_text='True after first invoice is created - prevents module deactivation', verbose_name='Module Activated'),
        ),
    ]
